export enum PATH {
  LOGIN = "/login",
  DASHBOARD = "/dashboard",
  TWO_FA_SETUP = "/two-fa-setup",
  TWO_FA_VERIFY = "/two-fa-verify",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  VERIFY_EMAIL = "/verify-email",
  HOME = "/home",
  CHANGE_PASSWORD_FIRST_TIME = "/change-password-first-time",
  ADMIN = "/admin",
  VOTER = "/voter",
  SECRETARY = "/secretary",
  USER = "/user",
  PRESIDE = "/preside",
  ORGANIZING_COMMITTEE = "/organizing-committee",
  BOARD_OF_CONTROL = "/board-of-control",
  HEAD_OF_THE_ORGANIZING_COMMITTEE = "/head_of_the_Organizing_committee",
  PRESIDE_APPROVED_REQ_FROM_USER = "/preside/decision-approval"
}
