export enum USER_ROLE {
  ADMIN = 'ADMIN',
  USER = 'USER',
  PRESIDE = 'PRESIDE',
  PRESIDE_SECRETARY = 'PRESIDE_SECRETARY',
  HEAD_OF_THE_ORGANIZING_COMMITTEE = 'HEAD_OF_THE_ORGANIZING_COMMITTEE',
  ORGANIZING_COMMITTEE_MEMBERS = 'ORGANIZING_COMMITTEE_MEMBERS',
  VOTER = 'VOTER',
  BOARD_OF_CONTROL = 'BOARD_OF_CONTROL',
}


export enum STATUS_ROLE {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  EXPIRED = 'EXPIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  ON_HOLD = 'ON_HOLD',
  NEW = 'NEW',
  CLOSED = 'CLOSED',
  OPEN = 'OPEN',
  LOCKED = 'LOCKED',
  UNLOCKED = 'UNLOCKED',
  VERIFIED = 'VERIFIED',
  UNVERIFIED = 'UNVERIFIED',
  SUBMITTED = 'SUBMITTED',
}


export const STATUS_ELECTION = {
  WAIT_APPROVAL: 'Chờ duyệt',
  DELETED: 'Đã xóa',
  WAIT_ENTER_DATA: 'Chờ nhập dữ liệu',
  ACTIVE: 'Đang hoạt động',
  INACTIVE: 'Không hoạt động',
}

export const STATUS_COLOR = {
  ACTIVE: '#52c41a',
  INACTIVE: '#bfbfbf',
}

export const PROGRESS_STATUS = {
  WAIT_APPROVAL: 50,
  WAIT_ENTER_DATA: 20,
  DELETED: 100,
  COMPLETE: 100
}

export const COLOR_ROLE = {
  USER: '#1890ff',
  ADMIN: '#fa541c',
  PRESIDE: '#722ed1',
}
